### PR TITLE
Sc0tts/fn geo step years

### PR DESCRIPTION
**Pull request by sc0tts**
The major goal of this pull request was to update FNGeo to use a year-long timestep instead of days.

Internally, it still uses dates, but timestep_duration is interpreted as dateutil.relativedelta(years=<val>) instead of datetime.timedelta(days=<val>).

I also cleaned up a lot of bad pythonic-ness in frost_number_Geo.py.  Still need to do the same for bmi_frost_number_Geo.py

Also, I'm not sure the output netcdf file is being written correctly, so I'll be looking at that also

### CODE REVIEW

**Comment by sc0tts** [comment]
Hmmm.  This is failing because of missing [dateutil.relativedelta](http://dateutil.readthedocs.io/en/stable/relativedelta.html) import?  I don't know why

**Comment by sc0tts** [comment]
I can't figure out why Py2.7 doesn't have dateutil.relativedelta.  

I tried adding 'dateutil' to setup.py, but that seems to have failed also....

Per [this post](http://stackoverflow.com/questions/8418636/python-cannot-find-dateutil-relativedelta), it would seem that on one's own system, it could just be re-installed:

   pip install python-dateutil --upgrade

**Comment by sc0tts** [comment]
So...the trick was not to require 'dateutil', but rather to require 'python-dateutil'

**Comment by sc0tts** [comment]
I looked at both conflicting files:
  permamodel/components/frost_number.py
  permamodel/tests/test_frost_number.py 

And they should both be updated to the version in this pull request, methinks

**Comment by mdpiper** [comment]
Merging. This is really close.

**Pull request merged**
