### PR TITLE
Sc0tts/calculate valid fn geo values wmt

### PR DESCRIPTION
**Pull request by sc0tts**
FNGeo had been set up to "grab" the relevant (min, max) temperature fields as they became available when the timestep reached appropriate values.  With the yearly timestep, this no longer worked.

Here, FNGeo can accept an array of monthly temperature fields -- exactly like those provided by the current cruAKtemp component! -- and extract a min (index 0 = Jan) and max (index 6 = Jul) field from that.  

Also provided here is a sample config file for WMT use when coupling with cruAKtemp:  
    permamodel/examples/FNGeo_WMT_testing.cfg

This code takes advantage of the BMI update_frac() routine to update the values of frostnumber without changing the time.  This permits initialization and loop steps like:

   init cruAKtemp
   init FNGeo
   update_cruAKtemp(0) [to copy it's 12-month temperature values to FNGeo]
   update_FNGeo(0)  [to update its frost number values using new temperature values]
   Loop while year < end_year:
      increment_year
      update_cruAKtemp()
      update_FNGeo
   finalize_FNGeo()

Note: the FNGeo output netcdf file is totally fubar with this commit.  It doesn't know about the new timestep unit of "years".

### CODE REVIEW

**Comment by mdpiper** [comment]
@sc0tts Thanks for your late-night work on this. I'll try to integrate these changes today.

**Comment by mdpiper** [comment]
Unfortunately, we can't use `atmosphere_bottom_air__temperature_months` from CRUAKTemp as it's currently set up -- the CMF doesn't work with lists, only with scalars and arrays. See https://github.com/permamodel/cruAKtemp/issues/8.

**Comment by sc0tts** [comment]
Instead of picking indexes 0 and 6 from an array/list of 12 monthly fields for the "current" year in WMT mode, this version now expects that the "jan" and "jul" fields will be provided as distinct arrays.

**Comment by sc0tts** [comment]
The most recent changes fix poorly coded get_value() and set_value() in the FNGeo BMI code.

Also, a directory has been added to the top level with code and config files that show an example of running cruAKtemp and FNGeo coupled together.

**Comment by mdpiper** [comment]
Not "poorly coded". This is a lack of documentation from us (CSDMS). I forgot that we needed to preserve references in the `get_value` and `set_value` methods.

**Pull request merged**
