### PR TITLE
Add initial commit of Frostnumber2D model

### PR DESCRIPTION
**Pull request by sc0tts**
This commit merges the work I did on the 2D version of the Frostnumber code.

Summary of changes:

1) Change the exclusions in .gitignore so that netcdf files *are* included (because the 2D version of Frostnumber requires a temperature "model", the data for which are in a netcdf file.

2) New code frost_number_2D.py and bmi_frost_number_2D.py are the new 2D version of the Frostnumber code

3) test_frost_number_2d.py is code to test the new code.

4) Several .cfg files are YAML files used as input to the 2D model.

### CODE REVIEW

**Comment by mdpiper** [comment]
Does the model require **cru_alaska_lowres_temperature.nc** to run, or is it just a sample input? I don't think input data should be included in the repository. If you need it for a test or an example, you should put it online somewhere (e.g., the CSDMS FTP site) and retrieve it as necessary.

**Comment by sc0tts** [comment]
The current tests do use **cru_alaska_lowres_temperature.nc**.  We could chat about how to get around that possibly?

**Comment by sc0tts** [comment]
Per our discussion (between Mark and Scott), let's hold off on accepting this pull request until the code is refactored to better isolate functionality:  The code should not depend on data being presented in a specific type of netcdf file.  And the data shouldn't be included in the code repository.

**Comment by Elchin** [comment]
Following up on cru_alaska_lowres_temperature.nc discussion. It would nice to include that cru dataset to the data folder. If the nc file is original file and not require post-processed then we can put a reference link to it.

**Comment by sc0tts** [comment]
I just pushed some more changes to the branch I'm using for this pull request.

Major changes are:
  - change name to FrostnumberGeo
  - change default config file so that values -- e.g. for testing -- can be entirely specified in the config file

Next steps:
  - change encoding of config file from yaml (current) which is Python-dependent to PermaModel style (based on TopoFlow)
  - ensure that bmi code is tested

Hmmm...  I see some fails in the Travis CI for this.  Will look into that.

**Comment by sc0tts** [comment]
There were two errors with the pull request.

One was because we'd changed the place where "examples_directory" was defined: from the __init__.py in the examples directory to the main __init__.py

The second was because I used the function np.stack() to combine 2D-arrays into a 3D-datacube.  But this function was added to NumPy in v1.10 and we must be using an earlier version in the Travis CI build.  

I fixed this by finding the code for np.stack() on NumPy's github repository and copying as a function into the code.  I included a reference to the original code and changed/added module names in the code so that it works.

**Comment by sc0tts** [comment]
I realized that the bmi code for FrostnumberGeo wasn't being tested!  The latest push corrects this.

**Comment by sc0tts** [comment]
These latest commits include bmi code that passes all but one test of the bmi-tester code.

That one, I may want to discuss with you guys this week.  Basically, the code was developed under conditions so that it could randomly-access temperature fields by date.  But in a WMT/BMI environment, this will need to change so that it grabs temperature fields as the time step moves forward, and saves the previous values that it needs to compute annual min and max.

**Comment by mdpiper** [comment]
Regarding 950f083: Don't copy code from numpy; we can include a **requirements.txt** to specify `numpy>=1.10`.

Update: see #32.

**Comment by sc0tts** [comment]
This version should work with WMT.  In WMT-mode -- which is set in the configuration file -- temperature is set by an array that is exposed to BMI calls.

**Comment by sc0tts** [comment]
Those latest three commits look good to me Mark; good work.

**Comment by mdpiper** [comment]
I'm preparing to merge this PR. There are still problems with FNGeo:

1. The time step should be years
1. I'm not sure `get_value` is working

but these can be addressed in a new branch.

The bigger problem is that there are overlapping commits between this PR and #42. The branches diverge after 5657e7a049a44b0dbba615059afb7a60b3952441. I'll try to rebase #42 on master after I merge this PR.

**Pull request merged**
