### PR TITLE
Update BMI metadata for FrostNumberModel

### PR DESCRIPTION
**Pull request by mdpiper**
I've performed some minor tweaks on the BMI metadata files for @sc0tts' FrostNumberModel. With these changes, I was able to babelize the model and turn it into a CSDMS component!

### CODE REVIEW

**Review by sc0tts — COMMENTED** [review]
Okay!  This is good to know.  I assume the same for everything at this "level" of the code, e.g. the Ku model.

**Review by sc0tts — COMMENTED** [review]
I (Scott) probably "broke" the package and class names when I separated all the BMI methods into the BmiFrostnumberMethod class.  Good catch.

**Review by sc0tts — COMMENTED** [review]
The "develop" vs "install" issue is just for the CI call, right?

**Comment by sc0tts** [comment]
All of these changes look good to me.  Should we designate someone to accept them?  Or just someone do so tomorrow.

**Comment by sc0tts** [comment]
I checked the details of the "All checks have passed" section.  I like that it automatically runs nosetests!

**Comment by mdpiper** [comment]
@sc0tts: I'm averse to merging pull requests I created, so if you're OK with the changes, please merge it.

**Pull request merged**
