### PR TITLE
cleaner test results

### PR DESCRIPTION
**Pull request by sc0tts**
I had originally opened this branch to track down a few remaining issues with leftover files from nosetests.  In the process, I learned a few things about how nosetests chooses the files that it runs when automatically collecting all the tests to run.

One of the benefits of the changes in this pull request is that an extraneous files that are created when running the standalone BMI routines for Ku model and Frost number are no longer generated when running nosetests.

Here are the changes:

1) In __init__.py, there was some old code about importing permamodel.utils and permamodel.components.  I think these are holdovers from Topoflow and are not needed.  I'm not completely sure, however.  So I left the code here but commented it out.  All tests still pass.

2) bmi_frost_number.py was unnecessarily printing its own memory handle.

3) added some info at the beginning of "run_bmi-tester_frostnumber" about how to invoke it.  Also moved this code from /tests subdirectory to /examples.

4) Moved the standalone run_test_BMI_... for frost_number and Ku models from the /tests to the /examples directories.  I think this is the more natural place for these example files to be located.

### CODE REVIEW

**Comment by mdpiper** [comment]
I think it's better to delete code than comment it. This is what version control is for! Plus, the commented code is distracting.

**Comment by sc0tts** [comment]
I'm good with deleting the (presumably) obsolete code.

And 'landscape' found some unused module imports too.  I can remove those.

I think the decrease in coverage/coveralls comes because these run_test_... examples were removed from the testing suite.  But this is misleading because they weren't really tests to begin with.

So...should I delete this pull request, make the changes in the code, and do a new pull request?  Or is there a way I can edit the code for this pull request?

**Comment by mdpiper** [comment]
Keep committing to this branch -- the changes will be included in this PR.

**Comment by sc0tts** [comment]
Okay...some obsolete code removed from __init__.py and also from run_test_BMI_*

**Pull request merged**
